# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: enterprise-systems
spec:
  owner: guest
  domain: party-domain
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: enterprise-systems
spec:
  owner: guest
  domain: account-domain
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: enterprise-systems
spec:
  owner: guest
  domain: product-domain
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: enterprise-systems
spec:
  owner: guest
  domain: transaction-domain
---
